board:
  starting_position:
    - [null, null, null, null, null, null, null, null]
    - [null, null, null, null, null, null, null, null]
    - [null, null, null, null, null, null, null, null]
    - [null, null, null, 'W', 'B', null, null, null]
    - [null, null, null, 'B', 'W', null, null, null]
    - [null, null, null, null, null, null, null, null]
    - [null, null, null, null, null, null, null, null]
    - [null, null, null, null, null, null, null, null]